development:
  adapter: postgres
  database: beatnode_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgres
  database: beatnode_test
  pool: 5
  username: postgres
  password: postgres
