development:
  adapter: postgres
  database: beatnode_development
  pool: 5
  username: beatnode
  password:

test:
  adapter: postgres
  database: beatnode_test
  pool: 5
  username: postgres
  password:
